### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by zoutepopcorn** [ianstormtaylor/permit#10]
I'm new to ES6 in Node. 

However getting some errors, when i try:
```javascript
// index.mjs
import {
  Bearer
} from 'permit'
console.log('auwa')
```

``` node -v => 10.0.0 ```

``` npm init . ```

``` npm i permit --save ```

## RUNNING
``` node --experimental-modules index.mjs ```
```
node --experimental-modules index.mjs 
(node:515) ExperimentalWarning: The ESM module loader is experimental.
file:///****************/index.mjs:2
  Bearer
  ^^^^^^
SyntaxError: The requested module 'permit' does not provide an export named 'Bearer'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:89:21)
```

Howto solve or run in another way?

**Comment by Kocisov** [comment]
```import Bearer from 'permit/lib/bearer'``` will work with modules flag 👋

**Comment by zoutepopcorn** [comment]
Thanks I will dive into Babel
