### ISSUE TITLE
fastify example broken

### ISSUE THREAD

**Issue by StarpTech** [ianstormtaylor/permit#7]
The current fastify example can't work because the interface is wrong. I think you copy & paste it from Koa.

Look here for [examples](https://github.com/fastify/fastify/tree/master/examples)

**Comment by ianstormtaylor** [comment]
Oh shoot, I must have accidentally overwritten the Fastify one when adding the Koa one. Thanks for reporting @StarpTech!

**Comment by StarpTech** [comment]
Should I help you out? I can create a PR.

**Comment by ianstormtaylor** [comment]
Closed by #9.
